version: "3"
services:
  redis4proxypool:
    image: redis:6.2.4-alpine
    container_name: redis4proxypool
    ports:
      - "6374:6379"
    restart: always
    volumes:
      - ./data:/data
    command: ["redis-server", "--appendonly", "yes"]
  proxypool:
    image: "k8scat/proxypool:latest"
    container_name: proxypool
    ports:
      - "5555:5555"
    restart: always
    #    volumes:
    #      - proxypool/crawlers/private:/app/proxypool/crawlers/private
    environment:
      REDIS_HOST: redis4proxypool
